// Generated by CoffeeScript 1.3.1
(function() {
  var sayHello;

  sayHello = function() {
    var b, f, h;
    f = document.createDocumentFragment();
    h = document.createElement('h1');
    h.innerHTML = 'Hello CoffeeScript';
    f.appendChild(h);
    b = document.body;
    b.appendChild(f);
    return f;
  };

  window.onload = sayHello;

}).call(this);
