// Generated by CoffeeScript 1.3.1
(function() {
  var sayHello;

  sayHello = function() {
    var h;
    h = document.createElement('h1');
    h.innerHTML = 'Hello CoffeeScript';
    return document.body.appendChild(document.createDocumentFragment().appendChild(h));
  };

  window.onload = sayHello;

}).call(this);
